name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-install-dependencies:
    uses: estefa-932014/devops-templates/.github/workflows/build/front/install_dependencies.yml@main
    with:
      node-version: '14'
