
    name: Caller Workflow
    on: [push, pull_request]
    jobs:
      build:
        uses: estefa-932014/my-react-app-vite-ghpages/.github/workflows/build/front/build-ci-react.yml@main
        with:
          node-version: '14'
