name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: estefa-932014/devops-templates/.github/workflows/main.yml@main
    with:
      node-version: '18.x'
